# Put this machine's brain on a live sync with the server. Run once per machine.
#
# The owner, 2026-09-04: "forget about github, github should be just a backup, the repo and the memory
# should all run locally syncing fetching etc" and "we need to fix this syncing live in the
# background on the other machines too."
#
# What this registers: HavokBrainSyncLive, running tools/pull-from-server.mjs --quiet every minute,
# starting at logon, with NO console window ever. A poll costs about 195ms and almost always stops
# at the /dist/version probe without transferring anything.
#
# WHY A .VBS WRAPPER. A scheduled task running node.exe directly flashes a console window on every
# fire, once a minute, forever. That was the exact complaint this work started from. WScript with
# window style 0 is the only reliable way to launch a console binary with no window on Windows.
#
# Idempotent: re-running replaces the existing task rather than erroring.

$ErrorActionPreference = 'Stop'

$brain = Split-Path -Parent $PSScriptRoot
$entry = Join-Path $brain 'tools\pull-from-server.mjs'
if (-not (Test-Path $entry)) { throw "pull-from-server.mjs not found at $entry" }

$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { throw 'node is not on PATH for this user' }

$configDir = if ($env:HAVOK_HOME) { $env:HAVOK_HOME } else { Join-Path $env:USERPROFILE '.claude' }
if (-not (Test-Path $configDir)) { New-Item -ItemType Directory -Path $configDir | Out-Null }

$token = Join-Path $configDir 'havok-server-token'
if (-not (Test-Path $token)) {
  Write-Warning "No server token at $token. The task will install but every run will no-op until"
  Write-Warning "the owner arms a bootstrap for this machine and it is collected."
}

# The launcher. Backslashes are NOT escaped: VBScript string literals have no escape character, so
# doubling them would produce a path that does not exist. A doubled quote IS one literal quote,
# which is how both paths survive having spaces in them.
$vbs = Join-Path $configDir 'havok-brain-sync.vbs'
$vbsBody = @"
' Generated by havok-brain\tools\install-sync-task.ps1. Launches the brain sync with no window.
Set sh = CreateObject("WScript.Shell")
sh.Run """$node"" ""$entry"" --quiet", 0, False
"@
Set-Content -Path $vbs -Value $vbsBody -Encoding ASCII

$taskName = 'HavokBrainSyncLive'
try { Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction Stop } catch { }

$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"' + $vbs + '"')

$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

$repeat = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddMinutes(1) `
  -RepetitionInterval (New-TimeSpan -Minutes 1)

# TWO things here each cost an "Access is denied" for a non-elevated user, and both were found by
# testing rather than by reading:
#   1. An EXPLICIT -Principal. Without one, registration is denied outright.
#   2. -AtLogOn scoped with -User. A bare -AtLogOn builds an ALL USERS trigger, which is an
#      administrative act. Same denial, and nothing in the message says which of the two it was.
# The failure is also non-terminating, so an earlier version printed "registered" straight over the
# top of the denial. That is why registration is verified against the scheduler below.
$desc = 'Keeps this machine''s brain mirror current from the server. No GitHub.'
$registered = $false
foreach ($who in @($env:USERNAME, "$env:USERDOMAIN\$env:USERNAME")) {
  try {
    $atLogon = New-ScheduledTaskTrigger -AtLogOn -User $who
    $atLogon.Delay = 'PT30S'
    $principal = New-ScheduledTaskPrincipal -UserId $who -LogonType Interactive -RunLevel Limited
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger @($atLogon, $repeat) `
      -Settings $settings -Principal $principal -Force -ErrorAction Stop -Description $desc | Out-Null
    $registered = $true
    Write-Output "principal   : $who"
    break
  } catch {
    Write-Output "principal   : $who rejected ($($_.Exception.Message.Trim()))"
  }
}
if (-not $registered) { throw "could not register $taskName as any form of the current user" }

# Never report success from the absence of a visible error. Ask the scheduler.
$check = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
if (-not $check) { throw "registration reported no error but $taskName does not exist" }

Start-ScheduledTask -TaskName $taskName
Start-Sleep -Seconds 8

$info = Get-ScheduledTaskInfo -TaskName $taskName
Write-Output "registered  : $taskName  (state $($check.State))"
Write-Output "launcher    : $vbs"
Write-Output "brain       : $brain"
Write-Output "last result : $($info.LastTaskResult)  (0 means the run succeeded)"
Write-Output "next run    : $($info.NextRunTime)"
Write-Output ('log         : ' + (Join-Path $brain '.pull-from-server.log'))
if ($info.LastTaskResult -ne 0) {
  Write-Warning "The first run did not return 0. Check the log above before trusting this machine."
}
